#!/usr/bin/env bash
# Displays IP and HTTP status code from Apache log file

while read -r line; do
	ip=$(echo "$line" | cut -d' ' -f1)
	status=$(echo "$line" | cut -d' ' -f9)
	echo "$ip $status
done < apache-access.log
