#!/usr/bin/env bash
#script that Creates the file /var/run/myscript.pid containing its PID
#script that Displays To infinity and beyond indefinitely
#script that Displays I hate the kill command when receiving a SIGTERM signal
#script that Displays Y U no love me?! when receiving a SIGINT signal
#script that Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

terminator() {
rm /vvar/run/myscript.pid
exit
}

echo "$$" > /var/run/myscript.pid
while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "Y U no love me?"' SIGINT
trap 'echo "I hate the kill command" && terminator' SIGTERM
trap 'terminator' SIGQUIT
done
