#!/urs/bin/env bash
#This script extends previous exercise command and displays line containing the word bash. Which allows one to easily get the PID of your Bash process.
#You cannot use pgrep
#shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
