#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with sleep 2
# Displays "I am invincible!!!" when receiving SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
