#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely
# script that displays With a sleep 2 in between each iteration
#  script that displays I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I  am invincible!!!"' 15
while true; do
echo "To infinity and beyond"
sleep 2
done
